
server:
  port: 8081
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    # 表示要订阅服务的服务名，可以配置'*'，代表订阅所有服务，不推荐使用。若需订阅多应用，使用 "," 分割
    subscribed-services: dubbo-spring-cloud-provider
#  application:
#    id: dubbo-consumer
#    name: dubbo-consumer
spring:
  application:
    name: dubbo-spring-cloud-consumer
  cloud:
    nacos:
    discovery:
      server-addr: localhost:8848
  main:
    allow-bean-definition-overriding: true